// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_impossible = "CgkIot63j_wSEAIQFw"; // <GPGSID>
        public const string leaderboard_distance_on_easy = "CgkIot63j_wSEAIQAw"; // <GPGSID>
        public const string achievement_appetizer = "CgkIot63j_wSEAIQDg"; // <GPGSID>
        public const string achievement_hardcore_collector = "CgkIot63j_wSEAIQGA"; // <GPGSID>
        public const string achievement_insane_falling_2 = "CgkIot63j_wSEAIQHw"; // <GPGSID>
        public const string achievement_hard_to_navigate_3 = "CgkIot63j_wSEAIQJw"; // <GPGSID>
        public const string achievement_insane_falling_3 = "CgkIot63j_wSEAIQKQ"; // <GPGSID>
        public const string achievement_more_stars_3 = "CgkIot63j_wSEAIQJg"; // <GPGSID>
        public const string achievement_a_good_start = "CgkIot63j_wSEAIQAg"; // <GPGSID>
        public const string achievement_more_stars_2 = "CgkIot63j_wSEAIQHA"; // <GPGSID>
        public const string achievement_hardcore_collector_3 = "CgkIot63j_wSEAIQLA"; // <GPGSID>
        public const string achievement_hardcore_collector_2 = "CgkIot63j_wSEAIQIg"; // <GPGSID>
        public const string leaderboard_distance_on_impossible = "CgkIot63j_wSEAIQBw"; // <GPGSID>
        public const string achievement_impossible_3 = "CgkIot63j_wSEAIQKw"; // <GPGSID>
        public const string leaderboard_distance = "CgkIot63j_wSEAIQEw"; // <GPGSID>
        public const string achievement_more_stars = "CgkIot63j_wSEAIQEA"; // <GPGSID>
        public const string leaderboard_stars_on_easy = "CgkIot63j_wSEAIQCA"; // <GPGSID>
        public const string achievement_next_level_3 = "CgkIot63j_wSEAIQJQ"; // <GPGSID>
        public const string achievement_next_level_2 = "CgkIot63j_wSEAIQGw"; // <GPGSID>
        public const string leaderboard_stars_on_normal = "CgkIot63j_wSEAIQCQ"; // <GPGSID>
        public const string achievement_impossible_2 = "CgkIot63j_wSEAIQIQ"; // <GPGSID>
        public const string achievement_appetizer_3 = "CgkIot63j_wSEAIQJA"; // <GPGSID>
        public const string achievement_appetizer_2 = "CgkIot63j_wSEAIQGg"; // <GPGSID>
        public const string leaderboard_stars = "CgkIot63j_wSEAIQFA"; // <GPGSID>
        public const string leaderboard_distance_on_normal = "CgkIot63j_wSEAIQBA"; // <GPGSID>
        public const string leaderboard_stars_on_hard = "CgkIot63j_wSEAIQCg"; // <GPGSID>
        public const string leaderboard_distance_on_hard = "CgkIot63j_wSEAIQBQ"; // <GPGSID>
        public const string leaderboard_stars_on_impossible = "CgkIot63j_wSEAIQDA"; // <GPGSID>
        public const string achievement_a_good_start_2 = "CgkIot63j_wSEAIQGQ"; // <GPGSID>
        public const string achievement_insane_collecting_3 = "CgkIot63j_wSEAIQKg"; // <GPGSID>
        public const string achievement_insane_collecting_2 = "CgkIot63j_wSEAIQIA"; // <GPGSID>
        public const string achievement_next_level = "CgkIot63j_wSEAIQDw"; // <GPGSID>
        public const string leaderboard_time_played = "CgkIot63j_wSEAIQDQ"; // <GPGSID>
        public const string achievement_hard_to_navigate_2 = "CgkIot63j_wSEAIQHQ"; // <GPGSID>
        public const string leaderboard_distance_on_insane = "CgkIot63j_wSEAIQBg"; // <GPGSID>
        public const string achievement_hardworking = "CgkIot63j_wSEAIQEg"; // <GPGSID>
        public const string leaderboard_stars_on_insane = "CgkIot63j_wSEAIQCw"; // <GPGSID>
        public const string achievement_hard_to_navigate = "CgkIot63j_wSEAIQEQ"; // <GPGSID>
        public const string achievement_a_good_start_3 = "CgkIot63j_wSEAIQIw"; // <GPGSID>
        public const string achievement_insane_falling = "CgkIot63j_wSEAIQFQ"; // <GPGSID>
        public const string achievement_insane_collecting = "CgkIot63j_wSEAIQFg"; // <GPGSID>
        public const string achievement_hardworking_3 = "CgkIot63j_wSEAIQKA"; // <GPGSID>
        public const string achievement_hardworking_2 = "CgkIot63j_wSEAIQHg"; // <GPGSID>

}

